name: Validate Presets
on: [push]
jobs:
  validate-presets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DCMAKE_INSTALL_PREFIX=/usr/local
    - name: Install Samples
      working-directory: ${{github.workspace}}/build
      run: sudo make install
    - name: Validate Presets Files
      working-directory: ${{github.workspace}}
      run: python3 Scripts/validate_presets.py -f presets.json
